### ISSUE TITLE
Form Exercise

### ISSUE THREAD

**Issue by DOkwufulueze** [OkwufuluezeD/html#1]
https://www.dropbox.com/s/utlctf92duufwyw/form.png is the URL of a Image (Form Image). You need to convert this image to an HTML form.

https://github.com/OkwufuluezeD/html/blob/master/danielFormExercise.html

**Comment by osifoanosike** [comment]
1. Try to use use HTML5-supported  tags only. E.g the following tags you used have been deprecated: <center>, <font>.

2. Your use of the table element doesn't seem most appropriate in this case, HTML5 sectioning and grouping elements would be more appropriate.

**Comment by osifoanosike** [comment]
1. Try to use use HTML5-supported tags only. E.g the following tags you used have been deprecated:
   `<center>`,`<font>`
2. Your use of the table element doesn't seem most appropriate in this case, HTML5 sectioning and grouping elements would be more appropriate.

**Comment by DOkwufulueze** [comment]
Feedback modifications implemented. Deprecated tags (center, font) removed, table, tr, td, th tags removed, replaced with section, div, span, and strong tags. Find the modified file in https://github.com/OkwufuluezeD/html/blob/master/form.html

**Comment by osifoanosike** [comment]
Please correct the spacing in your br tags, also I'd suggest you place the &nbsp; inside a content element rather than a grouping element. Fix this and close the issue

**Comment by DOkwufulueze** [comment]
Corrections implemented.
